Logs/urls.py
from django.shortcuts import render
from django.urls import path
from  Logs import views
app_name = "Logs"
urlpatterns = [
    path("" ,views.Home , name="Home"),

]

Testing_Djago_Apps/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("home/" , include("Logs.urls")),
]

Logs/models.py
from django.db import models
from django.db.models import Model

# Create your models here.


class Register(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    mobile_number = models.IntegerField(max_length=13)
    pan_card = models.CharField(max_length=12)
    

Logs/views.py
from django.shortcuts import render 
from django.http import HttpResponse
# Create your views here.
import logging
import os
from .models import Register

logging_str = "[%(asctime)s: %(levelname)s: %(module)s]: %(message)s"
log_dir = "log"
os.makedirs(log_dir, exist_ok=True)
logging.basicConfig(filename=os.path.join(log_dir,"ekyc_logs.log"), level=logging.INFO, format=logging_str, filemode="a")



def Home(request):
    if request.method == "POST":
        logging.info("Your request is post is succesfull lanuch ")

        first_name = request.POST['first_name']
        # print(first_name)
        last_name = request.POST['last_name']
        mobile_number = request.POST['mobile_number']
        pan_card = request.POST['pan_card']
        logging.info("Your All data is get !")
        if Register.objects.filter(pan_card=pan_card).exists():
            logging.info("This User Already present please show the login page")
            return HttpResponse("This is Login page beacuse you are alrady account")
        else:


            curr_data = Register( first_name=first_name, last_name =last_name ,mobile_number=mobile_number, pan_card=pan_card)
            curr_data.save()
            logging.info("Your Info save in this Tabkle Refistation   :"f"{first_name}{pan_card}")
            return render(request , 'home.html')
    else:
        logging.info("without post method call your page will we like this ")
        return render(request , 'home.html')

Logs/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>WelCome To My Regirstion Page!</h1>
    
    <form action="{% url 'Logs:Home' %}" method="post">
        {% csrf_token %}
        <label for="">first_name
            <input type="text" name="first_name" id="first_name">
        </label>

        <label for="">last_name
            <input type="text" name="last_name" id="last_name">
        </label>

        <label for="">mobile_number
            <input type="text" name="mobile_number" id="mobile_number">
        </label>

        <label for="">Pan_Card
            <input type="text" name="pan_card" id="pan_card">
        </label>

        <button type="submit">submit</button>
    </form>

</body>
</html>